# Generated by Django 5.0.6 on 2024-05-22 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripplans',
            name='package',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Packages.package'),
            preserve_default=False,
        ),
    ]
